# Generated by Django 5.2.9 on 2025-12-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_badge_product_colors_product_fit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='badge',
            field=models.CharField(blank=True, choices=[('NEW', 'NEW'), ('SALE', 'SALE')], max_length=20, null=True),
        ),
    ]
